/**
 * Installs the local-runtime launchers into ~/.crest/bin.
 *
 * The Agent/Runtime picker launches `<agent>-local` when an agent is pointed at
 * ollama. Those used to be zsh functions that only existed in one developer's
 * ~/.zshrc, so on any other machine Local mode was "command not found". Crest
 * now owns them: plain POSIX sh, rewritten on every launch so they track the app
 * version, and invoked by absolute path so a user's own same-named function can
 * never change what Crest runs.
 *
 * Each script points a cloud CLI at ollama without touching its normal config.
 * The model comes from CREST_LOCAL_MODEL; OLLAMA_HOST is honoured the same way
 * the ollama IPC probe honours it.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { homedir } from 'os'
import { join } from 'path'
import { LOCAL_BIN_DIR } from '../../shared/providers'

const PRELUDE = `#!/bin/sh
# Generated by Crest -- rewritten on every launch, edits will not survive.
set -e

MODEL="\${CREST_LOCAL_MODEL:-qwen3-coder:30b}"
case "$MODEL" in
  *[!A-Za-z0-9._:/@-]*) echo "crest: refusing odd model name: $MODEL" >&2; exit 2 ;;
esac

HOST="\${OLLAMA_HOST:-http://127.0.0.1:11434}"
case "$HOST" in
  http://*|https://*) ;;
  *) HOST="http://$HOST" ;;
esac
HOST="\${HOST%/}"

if ! curl -sf -o /dev/null "$HOST/api/tags"; then
  echo "crest: ollama is not reachable at $HOST" >&2
  echo "crest: start it with 'ollama serve' (or 'brew services start ollama')" >&2
  exit 1
fi

need() {
  command -v "$1" >/dev/null 2>&1 && return 0
  echo "crest: '$1' is not installed or not on PATH" >&2
  exit 127
}
`

const SCRIPTS: Record<string, string> = {
  // ollama serves an Anthropic-compatible /v1/messages, so the real binary
  // works unmodified.
  'claude-local': `need claude
ANTHROPIC_BASE_URL="$HOST" \\
ANTHROPIC_AUTH_TOKEN="ollama" \\
ANTHROPIC_MODEL="$MODEL" \\
ANTHROPIC_SMALL_FAST_MODEL="$MODEL" \\
API_TIMEOUT_MS="3000000" \\
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1" \\
exec claude "$@"
`,

  // Native OSS provider. Reasoning must be off: qwen3-coder rejects thinking
  // requests with a 400.
  'codex-local': `need codex
OLLAMA_HOST="$HOST" exec codex --oss --local-provider ollama \\
  -m "$MODEL" \\
  -c model_reasoning_effort="none" \\
  "$@"
`,

  // Thinking is a global Kimi setting and must be off for local models, so this
  // runs against its own KIMI_CODE_HOME and cloud Kimi (~/.kimi-code) is left
  // untouched. The config is regenerated each run so any picked model resolves.
  'kimi-local': `need kimi
KHOME="$HOME/.kimi-code-local"
mkdir -p "$KHOME"
cat > "$KHOME/config.toml" <<EOF
# Generated by Crest. Local ollama runs only; cloud Kimi uses ~/.kimi-code.
default_model = "local/current"
telemetry = false

[thinking]
enabled = false

[providers."ollama"]
type = "openai"
base_url = "$HOST/v1"
api_key = "ollama"

[models."local/current"]
provider = "ollama"
model = "$MODEL"
max_context_size = 65536
capabilities = [ "tool_use" ]
display_name = "$MODEL (local)"
EOF
KIMI_CODE_HOME="$KHOME" exec kimi -m local/current "$@"
`,

  // Speaks OpenAI natively, so it points straight at ollama's /v1.
  'qwen-local': `need qwen
OPENAI_API_KEY="ollama" \\
OPENAI_BASE_URL="$HOST/v1" \\
OPENAI_MODEL="$MODEL" \\
exec qwen -m "$MODEL" "$@"
`
}

/** Write the launchers. Never throws -- a failure only disables Local mode. */
export function installLocalAgentLaunchers(): void {
  if (process.platform === 'win32') return
  try {
    const dir = join(homedir(), LOCAL_BIN_DIR)
    mkdirSync(dir, { recursive: true })
    for (const [name, body] of Object.entries(SCRIPTS)) {
      const path = join(dir, name)
      const content = PRELUDE + '\n' + body
      if (!existsSync(path) || readFileSync(path, 'utf8') !== content) {
        writeFileSync(path, content, { mode: 0o755 })
      }
      chmodSync(path, 0o755)
    }
  } catch (error) {
    console.error('[localAgents] failed to install launchers:', error)
  }
}
